import { Inter } from "next/font/google";
import "./globals.css";
import { UserAuthContextProvider } from "../context/UserAuthContext";
const inter = Inter({
  subsets: ["latin"],
  weight: ["100"],
  variable: "--font--inter",
});

import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <UserAuthContextProvider>
          <SpeedInsights>{children}</SpeedInsights>
        </UserAuthContextProvider>
      </body>
    </html>
  );
}
